### ISSUE TITLE
不支持表格thead和图片吗？

### ISSUE THREAD

**Issue by lymallor** [JackGit/table2excel.js#1]
不支持表格thead和图片吗？

**Comment by JackGit** [comment]
@lymallor 
图片目前是不支持的，因为 ExcelJS 目前在 Browser 上的图片处理有些问题。
关于 thead，你最好能给出个有问题的例子。代码中没有特殊处理 thead tbody tfoot，只认 th tr

**Comment by lymallor** [comment]
@JackGit 不能导出不能以数字吗？可以的话，要配置什么呢？导出来者是文本，这样操作EXCEL不方便
