### ISSUE TITLE
导出的文件无法打开

### ISSUE THREAD

**Issue by ghost** [JackGit/table2excel.js#11]
我使用的环境是 webpack4+vue.js, 导出代码如下:
new Table2Excel("zd_table_trail").export("查询结果");
zd_table_trail是页面上表格的名字, 文件导出后无法打开, 
表格数据如下:
站点名称 | 记录时间
未分类站点 | 2018-09-05 21:50:07
我看您的代码可以导出纯数据, 所以打算用你的, 但是试了下, 无论是页面表格还是纯数据, 导出后都无法打开, 我在 office 和wps都试过, 均打不开!

**Comment by JackGit** [comment]
请提供 table html 结构。
另外，new Table2Excel() 的参数是 querySelector 字符串，你传的 "zd_table_trail" 是 class/name/id 还是什么？

**Comment by JackGit** [comment]
close it due to no more follow up
