### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by flatrow** [JackGit/table2excel.js#12]
Hi,

I tried to fork your repository and faced problems after build. When I use your dist, font colors and sizes in cells are the same as in an html table but with my dist I see default styles.

How do you build and are all changes pushed in repo?

Thanks,
Danila Alekseev

**Comment by JackGit** [comment]
@flatrow which version of exceljs did you use? And how did you use the lib, by script or by npm? If script, with the core or the full build?

**Comment by flatrow** [comment]
> @flatrow which version of exceljs did you use? And how did you use the lib, by script or by npm? If script, with the core or the full build?

ExcelJS version is 1.5.1
This is imported from npm package in table2excel.js src file

**Comment by JackGit** [comment]
I am not able to reproduce the issue anyway. If you can provide a mini sample your project, it would help.

**Comment by flatrow** [comment]
> I am not able to reproduce the issue anyway. If you can provide a mini sample your project, it would help.

http://dev.flatrow.com/table2excel/smth.html

**Comment by JackGit** [comment]
@flatrow tried your build [table2excel.min.js](http://dev.flatrow.com/table2excel/table2excel.min.js), it is not  exported some styles of font. Something must go wrong with your build steps, can you list the exact steps of your build process that starts from clone this repo?

Or may i know the reason you need your own build?

**Comment by flatrow** [comment]
@JackGit I need to format cells with numbers as numbers not as text and also to have custom names for sheets.

First change:
```
        cells.forEach(cell => {
            const { rowRange, colRange, el } = cell
            const { innerText } = el
            const workcell = mergeCells(worksheet, colRange.from, rowRange.from, colRange.to, rowRange.to)
            const cellStyle = getComputedStyle(el)

            workcell.value = this.isNumeric(innerText) ? parseFloat(innerText) : innerText

            // workcellCreated
            this._invokePlugin('workcellCreated', { workcell, cell: el, rowRange, colRange, cellStyle })
        })
```
```
    isNumeric(n) {
        return !isNaN(parseFloat(n)) && isFinite(n);
    }
```
Second change:
```
    constructor(selector = 'table', options = {}, names = []) {
        this.tables = Array.from(
            typeof selector === 'string'
                ? document.querySelectorAll(selector)
                : selector
        )

        this.names = names;
```
```
        tables.forEach((table, index) => {
            let worksheet;
            if (!this.names || !this.names[index]) {
                worksheet = workbook.addWorksheet(`Sheet ${index + 1}`);
            } else {
                if (this.names[index].length > 31) {
                    worksheet = workbook.addWorksheet(this.names[index].slice(0, 30))
                } else {
                    worksheet = workbook.addWorksheet(this.names[index])
                }
            }
```

**Comment by JackGit** [comment]
@flatrow Your requirements can be easily achieved by defining your own plugin.

```js
var myPlugin = {
  worksheetCreated: function (ctx) {
    ctx.worksheet.name = ctx.table.dataset.sheet
  },
  workcellCreated: function (ctx) {
    var value = ctx.workcell.value
    ctx.workcell.value = isNumeric(value) ? parseFloat(value) : value
  }
}
```

and then use it like: 
```js
new Table2Excel('table', {
    plugins: [
      Table2Excel.plugins.fontPlugin,
      Table2Excel.plugins.fillPlugin,
      Table2Excel.plugins.formPlugin,
      Table2Excel.plugins.alignmentPlugin,
      Table2Excel.plugins.hyperlinkPlugin,
      Table2Excel.plugins.autoWidthPlugin,
      myPlugin
  ] 
  })
```

The live example is [here](https://codepen.io/ygjack/pen/WazXXN)

**Comment by flatrow** [comment]
@JackGit thank you! I will try it.

**Comment by JackGit** [comment]
@flatrow you need latest publish, which is version 0.6.7.
Version 0.6.6 has plugin options issue

**Comment by flatrow** [comment]
@JackGit thank you, it works great.
