### ISSUE TITLE
隐藏在div中的table 无法下载

### ISSUE THREAD

**Issue by be1987** [JackGit/table2excel.js#13]
使用table2excel.core.js ,div中 设置为display: none 中的 table，下载后的 excel sheet 为空白

**Comment by JackGit** [comment]
@be1987 隐藏的 table 导出时无法准确计算样式，比如宽度。可能需要自己写 plugin 去操作这些。
下一个版本发布，会解决隐藏导出为空的问题，将会导出部分样式的表格。

**Comment by JackGit** [comment]
@be1987 试试安装 0.6.7 应该解决了问题

**Comment by be1987** [comment]
十分感谢您的答复，我先试一下
