### ISSUE TITLE
你好，字体加粗变大，表格加边框这些要怎么写？没看到说明

### ISSUE THREAD

**Issue by kkshell** [JackGit/table2excel.js#16]
$(document).ready(function () {
        $("#btnExport").click(function () {
            new Table2Excel('#test',  {
				  plugins: [{
				    workcellCreated ({ workbook, tables, worksheet, table, workcell, cell, cellStyle, rowRange, colRange }) {
				      workcell.style = {
				        ...workcell.style,
				        font: {“这里面怎么写，想操作单独的行或列呢”},
				        color: {“这里面怎么写，想操作单独的行或列呢”}
				      }
				    }
				}]
			}).export('日志', 'xls');
	    });
    });

**Comment by JackGit** [comment]
@kkshell 

workcell 怎么设置样式，具体参考 [exceljs#style](https://github.com/guyonroche/exceljs#styles)

整行整列设置有两种方式，一个是在 workcellCreated 阶段，通过 rowRange 和 colRange 进行判断是哪一行或者哪一列，然后控制是否做该单元格做样式设置。

rowRange 和 colRange 结构为：（如果单元格不跨多个行列，那么 from 和 to 值相同）
```js
cell.rowRange = { from: r, to: r }
cell.colRange = { from: c, to: c }
```

另外一种方式是，在 worksheetCompleted 阶段，直接操作 worksheet 对象，根据 exceljs api 操作修改整行整列的样式
