### ISSUE TITLE
Cannot read property 'el' of undefined

### ISSUE THREAD

**Issue by Farigen** [JackGit/table2excel.js#17]
Cannot read property 'el' of undefined
 at e.value (table2excel.min.js:8)

Here is something I find in your code in table2excel.min.js.
p = _.el: This _.el is undefined.
`for (var c = 0, f = 0; f < n; f++) for (var m = 0; m < i; m++) if (!u[f][m].cell) {
                        var _ = o[c++], p = _.el, y = p.rowSpan, g = p.colSpan;
                        _.rowRange = {from: f, to: f}, _.colRange = {from: m, to: m};
                        for (var v = f; v < f + y; v++) for (var M = m; M < m + g; M++) u[v][M].cell = _, _.colRange.to = M, _.rowRange.to = v
                    }`

My own code is involved with "rowSpan" and "colSpan".Hence this error occurs.

**Comment by Farigen** [comment]
Here is my table. By the way I use the bootstrap to decorate it.

<table id="show_table" class="table table-bordered table-condensed">
                        <tr>
                            <td colspan="2">测评项目</td>
                            <td>满意</td>
                            <td>基本满意</td>
                            <td>不满意</td>
                            <td>未测评</td>
                            <td colspan="2">测评项目</td>
                            <td>满意</td>
                            <td>基本满意</td>
                            <td>不满意</td>
                            <td>未测评</td>
                        </tr>
                        <tr>
                            <td class="vertical" style="vertical-align: middle" rowspan="5">饮食服务</td>
                            <td>食品安全</td>
                            <td id="11"></td>
                            <td id="12"></td>
                            <td id="13"></td>
                            <td id="14"></td>
                            <td class="vertical" style="vertical-align: middle" rowspan="6">校园服务</td>
                            <td>绿化养护</td>
                            <td id="15"></td>
                            <td id="16"></td>
                            <td id="17"></td>
                            <td id="18"></td>
                        </tr>
                        <tr>
                            <td>饭菜质量</td>
                            <td id="21"></td>
                            <td id="22"></td>
                            <td id="23"></td>
                            <td id="24"></td>
                            <td>道路保洁</td>
                            <td id="25"></td>
                            <td id="26"></td>
                            <td id="27"></td>
                            <td id="28"></td>
                        </tr>
                        <tr>
                            <td>服务态度</td>
                            <td id="31"></td>
                            <td id="32"></td>
                            <td id="33"></td>
                            <td id="34"></td>
                            <td>固定电话维护</td>
                            <td id="35"></td>
                            <td id="36"></td>
                            <td id="37"></td>
                            <td id="38"></td>
                        </tr>
                        <tr>
                            <td>就餐环境</td>
                            <td id="41"></td>
                            <td id="42"></td>
                            <td id="43"></td>
                            <td id="44"></td>
                            <td>信件收发</td>
                            <td id="45"></td>
                            <td id="46"></td>
                            <td id="47"></td>
                            <td id="48"></td>
                        </tr>
                        <tr>
                            <td>综合测评</td>
                            <td id="51"></td>
                            <td id="52"></td>
                            <td id="53"></td>
                            <td id="54"></td>
                            <td>浴室服务</td>
                            <td id="55"></td>
                            <td id="56"></td>
                            <td id="57"></td>
                            <td id="58"></td>
                        </tr>
                        <tr>
                            <td class="vertical" style="vertical-align: middle" rowspan="5">水电与维修服务</td>
                            <td>水电运行故障</td>
                            <td id="61"></td>
                            <td id="62"></td>
                            <td id="63"></td>
                            <td id="64"></td>
                            <td>综合测评</td>
                            <td id="65"></td>
                            <td id="66"></td>
                            <td id="67"></td>
                            <td id="68"></td>
                        </tr>
                        <tr>
                            <td>保修接待</td>
                            <td id="71"></td>
                            <td id="72"></td>
                            <td id="73"></td>
                            <td id="74"></td>
                            <td class="vertical" style="vertical-align: middle" rowspan="4">公寓服务</td>
                            <td>安全保障</td>
                            <td id="75"></td>
                            <td id="76"></td>
                            <td id="77"></td>
                            <td id="78"></td>
                        </tr>
                        <tr>
                            <td>维修响应时间</td>
                            <td id="81"></td>
                            <td id="82"></td>
                            <td id="83"></td>
                            <td id="84"></td>
                            <td>服务态度</td>
                            <td id="85"></td>
                            <td id="86"></td>
                            <td id="87"></td>
                            <td id="88"></td>
                        </tr>
                        <tr>
                            <td>维修服务质量</td>
                            <td id="91"></td>
                            <td id="92"></td>
                            <td id="93"></td>
                            <td id="94"></td>
                            <td>公共卫生</td>
                            <td id="95"></td>
                            <td id="96"></td>
                            <td id="97"></td>
                            <td id="98"></td>
                        </tr>
                        <tr>
                            <td>综合测评</td>
                            <td id="101"></td>
                            <td id="102"></td>
                            <td id="103"></td>
                            <td id="104"></td>
                            <td>综合测评</td>
                            <td id="105"></td>
                            <td id="106"></td>
                            <td id="107"></td>
                            <td id="108"></td>
                        </tr>
                        <tr>
                            <td class="vertical" style="vertical-align: middle" rowspan="5">物业管理</td>
                            <td>值班责任/态度</td>
                            <td id="111"></td>
                            <td id="112"></td>
                            <td id="113"></td>
                            <td id="114"></td>
                            <td class="vertical" style="vertical-align: middle" rowspan="5">车辆服务</td>
                            <td>安全行车</td>
                            <td id="115"></td>
                            <td id="116"></td>
                            <td id="117"></td>
                            <td id="118"></td>
                        </tr>
                        <tr>
                            <td>安全/服务意识</td>
                            <td id="121"></td>
                            <td id="122"></td>
                            <td id="123"></td>
                            <td id="124"></td>
                            <td>准点发车</td>
                            <td id="125"></td>
                            <td id="126"></td>
                            <td id="127"></td>
                            <td id="128"></td>
                        </tr>
                        <tr>
                            <td>楼内卫生保洁</td>
                            <td id="131"></td>
                            <td id="132"></td>
                            <td id="133"></td>
                            <td id="134"></td>
                            <td>车辆内外整洁</td>
                            <td id="135"></td>
                            <td id="136"></td>
                            <td id="137"></td>
                            <td id="138"></td>
                        </tr>
                        <tr>
                            <td>教学辅助服务</td>
                            <td id="141"></td>
                            <td id="142"></td>
                            <td id="143"></td>
                            <td id="144"></td>
                            <td>服务质量</td>
                            <td id="145"></td>
                            <td id="146"></td>
                            <td id="147"></td>
                            <td id="148"></td>
                        </tr>
                        <tr>
                            <td>综合测评</td>
                            <td id="151"></td>
                            <td id="152"></td>
                            <td id="153"></td>
                            <td id="154"></td>
                            <td>综合测评</td>
                            <td id="155"></td>
                            <td id="156"></td>
                            <td id="157"></td>
                            <td id="158"></td>
                        </tr>
                        <tr>
                            <td class="vertical" style="vertical-align: middle" rowspan="4">接待服务</td>
                            <td>御苑宾馆</td>
                            <td id="161"></td>
                            <td id="162"></td>
                            <td id="163"></td>
                            <td id="164"></td>
                        </tr>
                        <tr>
                            <td>明御楼</td>
                            <td id="171"></td>
                            <td id="172"></td>
                            <td id="173"></td>
                            <td id="174"></td>
                        </tr>
                        <tr>
                            <td>西苑招待所</td>
                            <td id="181"></td>
                            <td id="182"></td>
                            <td id="183"></td>
                            <td id="184"></td>
                        </tr>
                        <tr>
                            <td>综合测评</td>
                            <td id="191"></td>
                            <td id="192"></td>
                            <td id="193"></td>
                            <td id="194"></td>
                        </tr>
                    </table>

**Comment by JackGit** [comment]
@Lucas-Wang table 必须是一个完整的 [row * col](https://github.com/JackGit/table2excel.js#precondition) 的表，你的表最后 接待服务 后面缺东西，导致你的 table 不能被正确识别。也就是使用这个库，table 不能缺一块

**Comment by Farigen** [comment]
问题解决了，十分感谢!
