### ISSUE TITLE
隐藏内容不导出

### ISSUE THREAD

**Issue by yeungfujia** [JackGit/table2excel.js#20]
部分table中包含隐藏行，默认导出为全部能容，能否提供接口仅完成非隐藏内容导出

**Comment by JackGit** [comment]
@yeungfujia 能否提供一个样例 table

**Comment by JackGit** [comment]
你可以在 plugin 中处理，在 `worksheetCompleted` 钩子中，通过对 table 的查询，找到对应的行列信息，然后通过 ExcelJS api 对行或者列进行隐藏或者删除。

online demo:  https://codepen.io/ygjack/pen/qvyPxm

**Comment by yeungfujia** [comment]
> 你可以在 plugin 中处理，在 `worksheetCompleted` 钩子中，通过对 table 的查询，找到对应的行列信息，然后通过 ExcelJS api 对行或者列进行隐藏或者删除。
> 
> online demo: https://codepen.io/ygjack/pen/qvyPxm

我是使用的tablesorter带筛选功能的，筛选后隐藏列会有class="filtered"标识
![test](https://user-images.githubusercontent.com/36401123/54889405-67f08400-4edf-11e9-8461-16a95da0759b.png)

**Comment by JackGit** [comment]
@yeungfujia 对应的调整一下不就好了吗。
https://codepen.io/ygjack/pen/LaapqN
