### ISSUE TITLE
高度宽度怎么调呢

### ISSUE THREAD

**Issue by webjscss** [JackGit/table2excel.js#5]
如题。。

**Comment by JackGit** [comment]
高度是默认的，宽度自带的 autoWidth 插件能负责宽度。如果想自己设定宽度的话，需要对每个 cell
进行处理，具体可以参考 [autoWidth plugin](https://github.com/JackGit/table2excel.js/blob/master/src/plugins/autoWidth.js)

**Comment by webjscss** [comment]
表加了display:none 隐藏 导出 单元格 width就会不够。不加display 宽度正好能显示全 这个怎么解决呢 我看了下这个JS 这怎么用？

**Comment by JackGit** [comment]
display:none 之后，是无法计算显示宽度的，因为 getComputedStyle 无法获取正确的宽度。如果你一定要设置合适的宽度，只能通过 plugin，比如给每列各自设定合适的固定宽度

**Comment by JackGit** [comment]
close it due to no more follow up
