### ISSUE TITLE
Can I style borders ?

### ISSUE THREAD

**Issue by damien-monni** [JackGit/table2excel.js#6]
If I apply a border in CSS to my table cells, it is not exported in the Excel files. It is working with background-color for exemple, but not border.

Is it possible to add borders?

Thanks

**Comment by JackGit** [comment]
@damien-monni you may need to write your own plugin to export border styles.
The main idea is to create a conversion from html border style to excel border style. But the styles between these two are not one to one mapping, so you have to define yourself.

For excel border styles, please refer: https://github.com/guyonroche/exceljs#borders

I wrote a simply example to export border:

```
const borderPlugin = {
  workcellCreated: ({ worksheet, colRange, rowRange, cellStyle }) => {
    for (let c = colRange.from; c <= colRange.to; c++) {
      for (let r = rowRange.from; r <= rowRange.to; r++) {
        const cellPosition = Table2Excel.utils.cellPosition(c, r)
        const targetCell = worksheet.getCell(cellPosition)
        targetCell.border = domBorder2ExcelBorder(cellStyle)
      }
    }
  }
}

function domBorder2ExcelBorder (style) {
  const w = style.borderTopWidth.split('px')[0]
  const s = w > 1 ? 'thick' : 'thin'
  return {
    top: {style: s, color: {argb:'FF00FF00'}},
    left: {style: s, color: {argb:'FF00FF00'}},
    bottom: {style: s, color: {argb:'FF00FF00'}},
    right: {style: s, color: {argb:'FF00FF00'}}
  }
}
```

then use it like this:
```
new Table2Excel('table', {
    plugins: [
      Table2Excel.plugins.fontPlugin,
      Table2Excel.plugins.alignmentPlugin,
      Table2Excel.plugins.autoWidthPlugin,
      Table2Excel.plugins.formPlugin,
      Table2Excel.plugins.hyperlinkPlugin,
      borderPlugin
    ]
  })
```

**Comment by damien-monni** [comment]
Ok I see, thank you for this detailed answer!

**Comment by ghost** [comment]
add also -> Table2Excel.plugins.fillPlugin,
